# Generated by Django 6.0.1 on 2026-03-11 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_submission_submitted_at_alter_problems_hashed_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='description',
            field=models.TextField(default='No description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problems',
            name='hints',
            field=models.TextField(default='No hints'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problems',
            name='problem_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='problems',
            name='puzzel_content',
            field=models.TextField(default='No puzzel content'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problems',
            name='section',
            field=models.CharField(default='No section', max_length=150),
            preserve_default=False,
        ),
    ]
