# Generated by Django 6.0.1 on 2026-03-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_problems_description_problems_hints_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='problems',
            old_name='puzzel_content',
            new_name='puzzle_content',
        ),
    ]
