# Generated by Django 6.0.1 on 2026-03-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_rename_puzzel_content_problems_puzzle_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='problems',
            name='downloadable_file',
            field=models.FileField(blank=True, null=True, upload_to='challenge_files/'),
        ),
    ]
